# Generated by Django 3.2.9 on 2022-02-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pdf',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
