# Generated by Django 3.2.9 on 2022-02-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_message_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pdf',
        ),
    ]
